### ISSUE TITLE
DESIGN SUGGESTION: Missing page should let you navigate to edit

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-website#100]
Rather than just suggest you create a page in admin, why not have a link directly to edit if the user has admin privileges (and a different message if the user isn't admin).

![image](https://cloud.githubusercontent.com/assets/1531103/26807415/25f8876c-4a0b-11e7-8a64-84542aa7e97f.png)

**Comment by dtu-compute** [comment]
I suspect it would raise confusion among the users who are not used to wiki's. I'll close it for now and let's revisit it once it have been in production for a semester.
