### ISSUE TITLE
DESIGN SUGGESTION: Why not have edit link on every page?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-website#101]
Rather than going to the admin page to see the status, why not have an edit button/link (+ information about the page being locked) on each page, which shows up for admins?  That will make it a shorter trip to begin an edit..

**Comment by iainbryson** [comment]
Do you have a design preference for this?  I'm thinking a simple link button that lives either on or just under the nav bar, and is fixed on the screen.

**Comment by dtu-compute** [comment]
Perfect =)
