### ISSUE TITLE
Embedded images stopped working

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#118]
Might be related to no page linked to https://01005-enote.compute.dtu.dk/Semesteruge01S-Opgaver where the image is?

This might depend on #111

**Comment by iainbryson** [comment]
- [X] Designed
- [X] Implemented
- [X] Pushed to devel
- [X] Tested in devel2
- [ ] Tested in staging
- [ ] Tested in production
