### ISSUE TITLE
Errors won't update without page load

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-website#122]
I'm not sure how significant a problem this is, but errors are generated when you load the page.  Unlike the page list, which is a grid and can be updated client-side, there is no way to load the errors-only from the server.

So we can either turn the errors into a grid and follow the same style as the page list, or force a full page reload when making error-changing modifications.

**Comment by iainbryson** [comment]
- [X] Designed
- [X] Implemented
- [X] Pushed to devel
- [X] Tested in devel2
- [ ] Tested in staging
- [ ] Tested in production

**Comment by iainbryson** [comment]
From the "medium" tag, I assume that you want this resolved as I suggested above, to have the errors live update after a change?

**Comment by dtu-compute** [comment]
Both options are fine I think. Even a "Check all pages now for errors" button is fine. If you have a preference, then that's the one we take =)
