### ISSUE TITLE
Page operations may take a long time

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-website#123]
Due to the recent changes for errors, we have the following issue: All page operations (new, rename, delete) have the potential to affect all the errors:
(1) adds can remove errors
(2) page removal (either through delete or rename) can cause any file which references the page to have an error.

Similar issues exist with uploads and enotes, but those happen in batch mode, so an expensive recompile makes more sense.  FIle operations are interactive and so a long delay is more problematic.

Right now the solution is simply to recompile all the pages whenever we do one of these operations.  To make this faster we can:

(1) Upon a successful add, search the list of errors for "missing files" with the targetname the same as the newly-added file, and just recompile those
(2) Upon a successful delete, keep a map in memory from the last full compile of all the links, and only update those which target the deleted file.

**Comment by iainbryson** [comment]
We've resolved this in 2017 by adding the dialog.

**Comment by iainbryson** [comment]
In 2018 there are a lot of redesign questions which affect this: asciidoctor and moving to a static model.  This will still need to be tracked, but probably as part of the redesign rather than, as it is now, a bugfix/refactoring of the page editing feature.

**Comment by dtu-compute** [comment]
I have moved those two to 2019, so this ticket can be closed?
