### ISSUE TITLE
Update Sharelatex may take a long time

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-website#124]
get-pdf can take a very long time to compile the PDFs.

Currently, the modal "processing..." dialog alerts the user that this operation may take a while, but this is generally a suitable design for < ~10s.  Especially since we have no feedback from the getpdf process.

Also, typical HTTP request timeouts are 30s.

So we should really consider if this is the best design to have it as a button which the user clicks and probably expects a quick response.

(1) maybe this should be a non-UI operation: i.e. rake?
(2) or maybe this should use the [job framework in Rails](https://blog.codeship.com/how-to-use-rails-active-job/) -- intended for such long running operations.  This would optionally include a UI which would indicate details about any currently running job.

**Comment by iainbryson** [comment]
I think thus is a dupe of https://github.com/dtu-compute/dtu-enote-website/issues/163, no?

**Comment by dtu-compute** [comment]
Yes, closing this one.
