### ISSUE TITLE
enote menu not possible to read on small screens

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#144]
How difficult would it be to solve the below problem, where it is not possible to access the last pdf's on low res screens?

![1](https://user-images.githubusercontent.com/13518486/28260797-fe2322f4-6adc-11e7-9886-5c829436896e.png)

**Comment by iainbryson** [comment]
I think this might be a good solution:

https://stackoverflow.com/questions/19227496/scrollable-menu-with-bootstrap-3-menu-expanding-its-container-when-it-should-n

i.e. for specific sizes of screens, make the enote menu fixed and scrollable.

**Comment by dtu-compute** [comment]
Perfect =)
