### ISSUE TITLE
Set picture size

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#145]
Right now all pictures are scaled to 400px horizontally.

How difficult would it be to make it such that the picture width can be specified?

**Comment by iainbryson** [comment]
Looks like this isn't possible:

https://stackoverflow.com/editing-help#images

This suggest that there's another syntax, but it doesn't appear to work anymore (if it ever did)

https://stackoverflow.com/questions/29241776/pagedown-markdown-editor-issue-with-images

**Comment by dtu-compute** [comment]
Ok, thanks. I am closing.
