### ISSUE TITLE
Main restriction doesn't seam to be working

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#152]
The following should users to be logged in and be a member in `Main` to see it.

```
####### begin:only Main
only main
####### end:only
```

Instead it displays

```
only main 
```

Example https://01005-enote.compute.dtu.dk/MarkDown-Examples

**Comment by iainbryson** [comment]
When I'm not logged in, I see:

![image](https://user-images.githubusercontent.com/1531103/28374047-993eee36-6c71-11e7-8557-2ae5f72467e6.png)

When logged in with `enotema`, I see:

![image](https://user-images.githubusercontent.com/1531103/28374122-d1d1127e-6c71-11e7-8260-8f3253a6666d.png)


Which both seem as expected.

I see `only main` when logged in as `iajbrys`.  Perhaps the backdoor is adding me to `Main`?  There's not a config setting for which groups to add to, so I don't know which ones it adds to for certain, but I suppose either the backdoor or the users code will simply follow "admin for one group is admin for all".

**Comment by dtu-compute** [comment]
Actually ignore my OP, this is one of the vacation things again =)

Now I have changed the secret text, and I can see the secert text for `Main` and not for `A, B, biotek1` even though I am a member in A and B. `biotek1` doesn't exist anymore in the `01005-groups.yaml`. Could that be why I (and perhaps no one) can read the secret message?

**Comment by iainbryson** [comment]
Here the issue is different.  The code actually splits group names by ' ', not ',', so we end up looking for the following groups:

```
Array [ "", "A,", "B,", "biotek1" ]  application-6b59563d011038985adec62242456612868094f0d200559f2a2e0a6f9498532f.js:7:13128
```

None of these exist.  So the solution is to either change the markup to

```
####### begin:only A B biotek1
A secret only `A, B, biotek1` can read.
####### end:only
```

or change the code to remove ',' also.

Which do you prefer?

**Comment by dtu-compute** [comment]
Current is perfect. I am closing =)
