### ISSUE TITLE
enotes menu should not search directories

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#158]
Right now the website will add all pdf's in e.g `/vol/website-enotes/02323/` to the enote menu even if they are in a sub directory.

02323 would like to be able to have sub directories in `/vol/website-enotes/02323/` with pdf's (and aux files) that the website doesn't know about. They will use this to generate solutions and such together with the book in sharelatex. They then link to these in emails.

The menu should also ignore files that doesn't match `*.pdf`. Right now e.g. aux and txt files show up in the menu.

```
# tree /vol/website-enotes/02323/
/vol/website-enotes/02323/
├── chapter1-DataVisualization.pdf
├── chapter2-ProbabilitySimulation.pdf
├── chapter3-StatisticsNormalAssumption.pdf
├── chapter4-SimulationBasedStatistics.pdf
├── chapter5-SimpleLinearRegression.pdf
├── chapter6-MultipleLinearRegression.pdf
├── chapter7-ProportionsFrequencyTables.pdf
├── chapter8-StatisticsMultigroupANOVA.pdf
├── chapterA-formulas.pdf
└── files
    ├── book-IntroStatistics.aux
    ├── solutions-chapter1.pdf
    ├── solutions-chapter2.pdf
    ├── solutions-chapter3.pdf
    ├── solutions-chapter4.pdf
    ├── solutions-chapter5.pdf
    ├── solutions-chapter6.pdf
    ├── solutions-chapter7.pdf
    └── solutions-chapter8.pdf
```

**Comment by iainbryson** [comment]
First, getting it to ignore `.txt` and `.aux` should be quick and straightforward.

For the primary issue, if I understand correctly you want the menu structure to follow the folder structure, and not be flattened.  Is that it?  That should be possible, but will take more time.

**Comment by dtu-compute** [comment]
No, much simpler =) It should only include `/vol/website-enotes/02323/*pdf` and ignore everything else. =)

**Comment by dtu-compute** [comment]
It should also ignore directories.
