### ISSUE TITLE
Add new Admin->Course tab

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#160]
Add a new Admin->Course tab with

* "CampusNet course number" text entry box which only allows for numbers. This is the element number in `/vol/config/cn-dumper.yaml` and a Save button.
* "Course member lists was last updated" box which says when cn-dumper were last run.
* "CampusNet course name" box which displays the course name. cn-dumper needs to be updated to extract this info.
* "View users" button which just shows the users yaml file
* "View groups" button which just shows the groups yaml file

**Comment by iainbryson** [comment]
With this we should refactor the admin page into separate controllers; it's now very big and this would make it too big.

**Comment by iainbryson** [comment]
Do you have information on how this is to be done:

> "CampusNet course name" box which displays the course name. cn-dumper needs to be updated to extract this info.

?

**Comment by iainbryson** [comment]
When you say:

> "View users" button which just shows the users yaml file
> "View groups" button which just shows the groups yaml file

Do you mean the actual files themselves, or the information that we've parsed from the files?

**Comment by dtu-compute** [comment]
Showing the actual yaml file is acceptable. If you can find an easy way to display its parsed content, then that would probably be preferred.

**Comment by iainbryson** [comment]
When we update the course number -- is that it?  i.e. just update `cn-dumper.yaml` and wait for the cron job to update?  It seems like there ought to be an update button to refresh?

**Comment by dtu-compute** [comment]
It would be great with an Update. Can it be added easily?

**Comment by iainbryson** [comment]
Unfortunately it's not so simple.  It requires running scripts in two separate containers (and building the cndumper one)  That's only possible on the host.  It would take some effort to figure out a mechanism to kick off the scripts on the host.

**Comment by dtu-compute** [comment]
Ok, then no Update button =)
