### ISSUE TITLE
Redis for soft state

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#164]
https://github.com/dtu-compute/dtu-enote/issues/66 is related to this ticket.

All of the state in the course rails app is on disk because of the requirement not to use a database. This causes things problems like not being able to use a rake task to affect the state of the running
course (e.g. adding PDFs won’t show up until the site is rebooted to an update is triggered.

How would you feel about storing that kind of soft state in redis? I know this changes the design you were looking for, but it’ll make the site work reasonably when we have external jobs modifying its
state.

**Comment by iainbryson** [comment]
Since this is in the 2018 list, I assume that's a yes on this being desireable?

:)

**Comment by dtu-compute** [comment]
Absolutely =)
