### ISSUE TITLE
Stackedit / Leanote editor

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#165]
Leanote have forked the StackEdit editor and parser at https://github.com/leanote and made them into separate projects. In v2 it looks like he have even added Vim and Emacs mode options.

If, can we then easily get that editor?

**Comment by iainbryson** [comment]
I'm a little confused here.  We went away from StackEdit in 2016 to the custom editor in 2017, now you want to go back?  So I understand, what are the main features/functionality that this is intended to provide?

**Comment by dtu-compute** [comment]
This ticket is of course in conflict with the one about going to asciidoc, where the asciidoc one is the most important of the two.

I recall you said that extracting just the editor from Stackedit would be a large task and it looks like this guy have done all the hard work. It is a nice editor, so if it would be little effort to replace the current with this one, then it would be interesting.

But again, if it turns out that asciidoc(tor) is great and it makes a lot of sense, then this ticket can just be closed.

**Comment by iainbryson** [comment]
Since Ascii doc looks feasible, I suppose we should de-prioritize this one until/unless we discover something problematic about the move to asciidoc.

**Comment by dtu-compute** [comment]
Yes, let's ignore this one for now.
