### ISSUE TITLE
Long left page doesn't trigger scrollbar

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#180]
![screenshot from 2018-03-29 13-03-32](https://user-images.githubusercontent.com/13518486/38085999-1278ef6a-3353-11e8-837f-3efccc8eff0f.png)

**Comment by iainbryson** [comment]
This is by design, no?  https://github.com/dtu-compute/dtu-enote-website/issues/162

**Comment by dtu-compute** [comment]
Good point. Closing.
