### ISSUE TITLE
Inline quizzes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#184]
Inline quizzes should be very similar to the hint and answer blocks/buttons which the website supports now and the [Stanford quiz](http://web.stanford.edu/class/ee103/quizzes/vectors.html). Just like these, inline quizzes should not have communication with the back end. It is just html with a bit to JS to show/hide the answers.

The test case that should work is

```
Some regular website text here.

####### begin:quiz
begin:multiple_choice
  wrong "54.5"
  right "The median for the data in $b$ is approximately $8\sqrt{\frac{1}{x}}$"
  wrong "The data in boxplot $c$ has the smallest variance"
  wrong "52.6"
end:multiple_choice
####### end:quiz

Some regular website text here.

####### begin:quiz
begin:all_that_apply
  right 'right one'
  wrong 'wrong one'
  wrong 'not this one'
  right 'select this one as well'
end:all_that_apply
####### end:quiz

Some regular website text here.

####### begin:quiz
begin:fill_in_the_blank
  text 'Which %4% %2% missing %1%'
  right 'This is the solution I thought of. 'word, is, ?'. There might be others.'
end:fill_in_the_blank
####### end:quiz
```

In the test case have only used single line options and replies. It would be really good if `begin/end: right, wrong, text` worked as well.

**Multiple choice**
The Stanford doesn't have the radio buttons, but ours should, so it looks like the one from DTUquiz.

**All that apply**
Submit on ours it is like the Stanford, expect it shouldn't put the X's and V's.

**Fill in the blank**
Submit it shows the text from the 'right' string.

**Comment by iainbryson** [comment]
Regarding fill in the blank:

```
####### begin:quiz
begin:fill_in_the_blank
  text 'Which %4% %2% missing %1%'
  right 'This is the solution I thought of. 'word, is, ?'. There might be others.'
end:fill_in_the_blank
####### end:quiz
```

Do you want this new syntax (i.e. the "right" clause) to be acceptable for the quiz or not?  I'm basically asking whether I should add it to the quiz parser or keep it only in the course.  Of course it would be more work to actually implement it on the quiz size (i.e. to do something useful), but my question is whether it should even parse.

**Comment by dtu-compute** [comment]
Let's wait with adding it to the quiz.

**Comment by dtu-compute** [comment]
Could it be like the others where only single or double quotes are allowed?

```
  right 'This is the solution I thought of. "word, is, ?". There might be others.'
  right "This is the solution I thought of. 'word, is, ?'. There might be others."
```

Or wouldn't that help?
