### ISSUE TITLE
Fill in the blank feedback color

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#189]
```
####### begin:quiz
begin:fill_in_the_blank
  text 'Which %4% %2% missing %1%'
  right 'word' 'is' '?'
  wrong "some feedback"
end:fill_in_the_blank 
####### end:quiz
```

Clicking Submit: if correct, the bg of the typed text becomes green else red. Only if one or more is wrong, add a red bg feedback line which is the content of `wrong`.

**Comment by dtu-compute** [comment]
Correction: Only show feedback is wrong, where question and feedback gets red bg. If correct, then only the question gets a green bg.

**Comment by iainbryson** [comment]
I think I’ll need a lot more clarification on this.  How do you expect that the fill in the blank will understand what’s correct and what isn’t?

In the prototypical example you provided:

```
####### begin:quiz
begin:fill_in_the_blank
  text 'Which %4% %2% missing %1%'
  right 'This is the solution I thought of. 'word, is, ?'. There might be others.'
end:fill_in_the_blank 
####### end:quiz
```

It’s not clear how the system would parse the “right” text to determine that’s correct and what’s not.  If we want to have verification, then it would make a lot more sense IMO to follow the `right` syntax like the other questions, e.g. one `right` per blank, with two arguments, one for the correct string and one for the feedback text, e.g.:

```
####### begin:quiz
begin:fill_in_the_blank
  text 'Which %4% %2% missing %1%'
  right 'word' "some feedback"
  right 'is' "some feedback"
  right '?' "some feedback"
end:fill_in_the_blank 
####### end:quiz
```

But of course, the quiz itself doesn't do any verification of fill in the blank.

**Comment by dtu-compute** [comment]
Good point. I have now updated OP, so we can iterate on a solution for this.

And welcome back btw. Have a week already passed? =)
