### ISSUE TITLE
Minor chat fixes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#197]
* Feedback buttons and chat swap places.
* Don't open chat when clicking e.g. on the places where the red X are on below screenshots.
* Remove extra column marked with red
* shrink chat to 75% of with current width, so it hopefully doesn't overlap website content.

![screenshot from 2018-06-11 13-43-36](https://user-images.githubusercontent.com/13518486/41230167-074279ac-6d7f-11e8-8a41-c2eb65532662.png)

**Comment by iainbryson** [comment]
Status for tracking:

- [ ] Feedback buttons and chat swap places.
- [ ] Don't open chat when clicking e.g. on the places where the red X are on below screenshots.
- [ ] Remove extra column marked with red
- [ ] shrink chat to 75% of with current width, so it hopefully doesn't overlap website content.
