### ISSUE TITLE
"CampusNET Participants URL:" regex

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#208]
Can the "CampusNET Participants URL:" regex handle URL's of these forms?:

```
https://cn.inside.dtu.dk/cnnet/element/572973
https://cn.inside.dtu.dk/cnnet/element/578415/participants
```

Ideally it should just take the last 6 digits from the string.

**Comment by iainbryson** [comment]
Is should do this already, at least find the first 6 digit number.  Do you not see that, or do the other bugs obscure it?
