### ISSUE TITLE
Local exercise numbering also for `###`.

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#220]
At https://01005.compute.dtu.dk/EU06S-OPG#1 are the headings using `###` and the exercise numbering is global.

At https://01005.compute.dtu.dk/EU02S-OPG#1 are the headings using `##` and the exercise numbering is local.

They would like to have local exercise numbering also for `###`.

**Comment by iainbryson** [comment]
Can you give some more details on what you want?   i.e what changes to the generated html you'd like?  I'm pretty sure the design right now is that exercises are numbered according to the nesting of the headings, as X.Y.Z, with X, Y and Z being the index of the the current h1, h2 and h3 (i.e. #, ##, and ###) respectively.

I don't really remember the concept of global and local numbering?

**Comment by dtu-compute** [comment]
When global exercise were added it was apparently only for `###`. If you look at the two links, then the header determines if you get global or local.

So Karsten would like that he also get local numbering when using `###`.

Does that make sense?
