### ISSUE TITLE
List of missing pages

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#53]
On a fresh install the menu pages are missing by design.

It would be great if `Admin->StackEdit->Parse Errors` could list the missing pages with the name of the page that should be created in StackEdit.

**Comment by iainbryson** [comment]
To make this a clearer, there should be a parse error if any of the "root" pages are missing: "Agendas.md", "Frontpage-right.md", "Frontpage-left.md", etc..", and then additional errors for any Agendas links which do not have a page.

Is that correct?

**Comment by dtu-compute** [comment]
Yes, exactly.
