### ISSUE TITLE
Delete download scripts?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#55]
Can

https://github.com/dtu-compute/dtu-enote-website/blob/devel/do-download.js
https://github.com/dtu-compute/dtu-enote-website/blob/devel/download-all-docs.js

be deleted now that we have `couchdb_*` in https://github.com/dtu-compute/dtu-enote-stackedit ?

**Comment by iainbryson** [comment]
These scripts are used by the update service in the Web site -- when you click update stackedit.  The couchdb_* scripts are similar, but are meant for operators (i.e. people) to load/extract files. We could try to merge the sets of scripts.  We'll need to figure out how to share the scripts between the two containers to make that work.

Do you want to do that, or leave them as is?

**Comment by dtu-compute** [comment]
Perfect as is =)
