### ISSUE TITLE
begin/end only block doesn't restrict content

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#60]
Testing the below on the 00000 which according to Admin->StackEdit tab have `Main` as a valid group.

The expected would have been that the first case should give an error, as A, B, biotek1 groups doesn't exist.

For the second case,  it parses and removes the `####### begin:only Main` but still writes the content even when I am not logged in. The idea is that writing the below would require the visitor to be logged in.

```
####### begin:only A, B, biotek1
Here is content that only students in the classes `A, B, biotek1` can see.
####### end:only

####### begin:only Main
only main
####### end:only
```

**Comment by dtu-compute** [comment]
If a user belongs to group A, can he then View Source and see content that he doesn't have permission for?

**Comment by iainbryson** [comment]
Ah, my mistake.  Yes, currently the group enforcement is done client-side, so view source will show it.  I had the impression that doing it client-side was OK, but looking at Issue#9 you clearly said "server side".  I'll fix that up right away.
