### ISSUE TITLE
View hint/result corrupts MathJax

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#67]
One of the professors can reproduce on his Mac and Windows, that when he clicks either View Hint or View Result then the MathJax on the page gets corrupted. If however he does it in incognito then it works. Another professor sees the same issues. Both have the latest version of Firefox and Chrome. I can't reproduce it on my machine.

![1](https://cloud.githubusercontent.com/assets/13518486/22061131/e8330c76-dd73-11e6-959d-736d7b2dc2f7.png)

**Comment by iainbryson** [comment]
Can you get the .md of the exercise which exhibits this behavior?

**Comment by dtu-compute** [comment]
It is this one `/vol/website-raw/01006/Week-1-Wed-1.md`

Copy/pasted below as well

```
#Exercise 1 Approximating Polynomials


a) Maple-opgave:
Use Maple to find the approximating polynomial of degree 9, $P_9(x)$ with the development point $x_0 = 0$ for the function $\sin(x)$. Draw in the same coordinate system $\sin(x)$ and  $P_9(x)$. How far out can you make the approximating poynomial follow the function? (Experiment wit the degree of the polynomial).
####### begin:answer
The higher the degree of the approximating polynomial the larger the interval around $x_0 = 0$ there will be agreement between $\sin(x)$ and the appoximating poynomial $P_9(x)$. One can make the approximating poynomial  $P_9(x)$ follow $\sin(x)$ as long as you like, because $\sin(x)$ is analytic for all $x$. For $n = 17$ it agrees with $\sin(x)$ in the interval $[-2\pi;2\pi]$ and for $n = 25$it is even better.
####### end:answer

b) Exercise by hand followed by a maple plot:
Find for every of the following functions their approximating poynomials of first and second degree with the development point $x_0 = 0$ and plot each of the functions together with the two approximating polynomials found:

1. $f(x) = e^x$,
2. $f(x) = \cos(x)$,
3. $f(x) = e^{\sin(x)}$,
4. $f(x) = \cosh(x)$.

####### begin:answer
1. $P_1(x) = 1+x$ and $P_2(x) = 1+x+\frac{1}{2}x^2$,
2. $P_1(x) = 1$ and $P_2(x) = 1-\frac{1}{2}x^2$,
3. $P_1(x) = 1+x$ and $P_2(x) = 1+x+\frac{1}{2}x^2$,
4. $P_1(x) = 1$ and $P_2(x) = 1+\frac{1}{2}x^2$.
####### end:answer
```

**Comment by iainbryson** [comment]
Strange.  I just tried on Mac OS 10.12.2 With Safari 10.0.2, Chrome 55, and Firefox 50. None of them showed the issue.

Can you get specific OS/Browser versions where the problem shows up?

**Comment by dtu-compute** [comment]
I know he used Firefox 50.1.0 but have seen him reproduce it with Chrome as well. Another professor can reproduce it too.

When I used Incognito mode on his computer it worked, so it have to do something with a caching problem I assume.

When I try with Firefox and Chrome I can't reproduce it.

**Comment by iainbryson** [comment]
I noticed a couple of things in the image:
(1) There are answers there, no hints or results.  Is that just a naming issue?
(2) The messed up markup looks like it came before pressing on the buttons -- neither of the two "answers" on the page have been clicked
(3) There are a bunch of [Math Processing Error] on the page

Since I can't seem to reproduce it on Mac OS using any of the 3 browsers I have, probably the only thing to do is to see if we can get the professors to provide more information, via the web debugger in the browsers.  The console should give a bit more information about the errors.

**Comment by dtu-compute** [comment]
I am not sure I understand your (1) point.

(2) Good point. I don't why he told me that it occurred when pressing the buttons.

(3) I'll get those for you and post them here.

**Comment by iainbryson** [comment]
Point 1 is this: We only support begin/end with the following directives:
`only|hint|answer|question`.  The bug report says the issue is with “view
hint” and “view result”.  The screenshot is with “answer” elements.  Is
that what’s meant by “view result”?

**Comment by iainbryson** [comment]
OK. I've added the report-a-bug button to both the quiz and the course Web site. That should help figure out what went wrong when the issue is noticed.  It should log mathjax rendering errors back to the service

**Comment by dtu-compute** [comment]
I can now reproduce it on my desktop every time.

1. `rm -rf .mozilla/ && firefox`
2. 01006-compute.dtu.dk
3. Click Login
4. Click Admin
5. Click Week-1-Wed-1
6. Wait 5 seconds
7. Click browser back button
8. Click Week-1-Wed-1
9. Wait 5 seconds.
10. Corrupt math appears

**Comment by iainbryson** [comment]
Ok!  I'm pretty sure I have an idea of what's going on here.  It looks like we're starting two renders of the same page when reloading via turbolink. There's a race condition and one of the renders causes the other to crash.

The fix should be straightforward, but the code has diverged significantly between 2016 and devel.  Do you want a fix in devel only, or both 2016 and devel?  

FWIW, it doesn't seem to reproduce in the same way in devel at the moment (the repro case is the page called `bug67`.  It works just fine for me, whereas I can reproduce the failure using your steps on the 2016 site with `Week-1-Wed-1`.

**Comment by dtu-compute** [comment]
Interesting!

My thought was to deploy devel on staging for the demo and let them use that one until we deploy devel to production.

Ok, so if it looks like it have been fixed in devel, then that is great =)

**Comment by iainbryson** [comment]
Sounds good.  I've done a bit more refactoring of the page startup code to make this more robust and deploy it to devel later today.  Can you validate that it no longer fails in the same way there?

**Comment by dtu-compute** [comment]
Sounds good. I have just tried on devel2, and I can't create new pages. Tried e.g. with `aaa`.  Chrome console gives
```
Uncaught TypeError: Cannot read property 'page_index_url' of undefined
    at HTMLButtonElement.<anonymous> (application-0d7109f….js:8)
    at HTMLButtonElement.dispatch (application-0d7109f….js:2)
    at HTMLButtonElement.y.handle (application-0d7109f….js:2)
```

I'll try again later today.

**Comment by iainbryson** [comment]
Yeah, sorry to be unclear, I meant I’d finish and deploy by the end of my
day.  I’ll send a note when that’s done and tested.

**Comment by dtu-compute** [comment]
Can reproduce on devel2 by

* `rm -rf .mozilla/ && firefox 00000-devel2.compute.dtu.dk`
* paste in `https://00000-devel2.compute.dtu.dk/bug67`
* click agendas
* cleck back button
* click agendas
* paste in `https://00000-devel2.compute.dtu.dk/bug67`
* click agendas
* cleck back button

**Comment by iainbryson** [comment]
Wow, this is super tricky.

So I know what's going on, if not why. Here's the story:

If you load a page via turbolinks (as you do with the back arrow), **and that page has hints** then the the MathJax render will get corrupted.  For whatever reason, it seems it having `display:none` elements in the DOM during a tubolink reload (but not a normal one) will cause corruption.

https://www.peterkrautzberger.org/0165/ gives a hint as to what's going on.  The combination of loading the page via AJAX (which is what turbolinks do) and then mathjax's display:none special casing is likely too confusing.

So for now I'll go with the best practice described above, using `visibility:hidden`.  If that doesn't work 100%, then we should just get rid of tubolinks entirely; the performance benefit is not worth the added complexity if this bug is any indication...

**Comment by dtu-compute** [comment]
Wow! Strange that something like this limitation isn't somewhere very visible on the MathJax website, as it is so critical for it to work properly.

Very nicely debugged =)

**Comment by dtu-compute** [comment]
I actually had wondered why we hadn't seen this bug in the quiz, but now it makes sense =)

**Comment by iainbryson** [comment]
Yes, it’s a different use case there. It’s also a somewhat different rendering pipeline: the one in the Web site was forked from StackEdit (which is mostly the same as the editor code too, being forks of Stackexchange’s code.

I’ve deployed the latest fix to devel2.  Can you check it out?  After so many iterations I don’t have the courage to say it’s the last :S

**Comment by dtu-compute** [comment]
I think you nailed it =) Ahh, it is going to feel good to click the close button on this one =)
