### ISSUE TITLE
In some cases Podcast page works

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#70]
There is an issue somewhere to get the podcast page to display, and I haven't yet figured out how to reproduce it, but that will come shortly.

Can you take a look at [this](https://github.com/dtu-compute/dtu-enote-website/commit/d6bbb07ee9b2fb8c89a5526055db624fa90a79ee) commit and tell if it is correct that you have written `Podcast-Right.md` and not `Podcast-right.md`?

**Comment by iainbryson** [comment]
Yeah, that's a bug.  It should be always `-right`.  That would at least make things confusing in the rendering, and maybe account for things not showing up.  Though it should be deterministic.

Note that there's nothing special about the Podcast prefix, just the exact names Podcast[-right|-left]. So if there's a bug in getting the name right, you should always be able to navigate to the the page as "just a normal md rendered page"

**Comment by dtu-compute** [comment]
Ok, so I think this is the problem:

On 02323 I have `Podcast-left` and `Podcast-Right` and renamed all the old -i `Podcasts?` files to start with an x.

Looking in `/vol/website-raw/02323` the old podcast files are still there. It seams that ones a filename have been used once, it is never deleted when renaming the file in StackEdit.

https://02323.compute.dtu.dk/podcast right now doesn't display the right part, and I assume that is because of the above.

Looking at https://02323.compute.dtu.dk/Podcast-left things looks right, but the podcast isn't inserted in https://02323.compute.dtu.dk/Podcast-Right as expected.

Is it the old files that are blocking the podcast from being rendered?

**Comment by iainbryson** [comment]
This is the error I see in the logs:

```
I, [2017-02-03T16:13:44.240910 #112]  INFO -- : Loading Podcast.md from /data/course-website-raw/Podcast-Right.md
I, [2017-02-03T16:13:44.312181 #112]  INFO -- : Completed 500 Internal Server Error in 937ms
F, [2017-02-03T16:13:44.313117 #112] FATAL -- :
JSON::ParserError (784: unexpected token at '<html><body>You are being <a href="https://auth.dtu.dk/dtu/login?service=https%3A%2F%2F02402.compute.dtu.dk%2Fpodcast%2Findex&amp;gateway=true">redirected</a>.</body></html>'):
  app/services/update_service.rb:83:in `block (2 levels) in refresh_podcasts'
  app/services/update_service.rb:77:in `each'
  app/services/update_service.rb:77:in `block in refresh_podcasts'
  app/services/update_service.rb:76:in `open'
  app/services/update_service.rb:76:in `refresh_podcasts'
  app/controllers/admin_controller.rb:86:in `update'

```

It looks like the url http://podcast.llab.dtu.dk requires auth.  I put in a workaround for this in devel when I noticed the issue in the logs, but failed to connect the dots to this bug.  But all that does is stop the exception, not actually perform the auth.  If we need to do that, we’ll need to reconsider the design…

**Comment by dtu-compute** [comment]
Ok, that is super odd. When I open `http://podcast.llab.dtu.dk/feeds/02402-introduction-to-statistics-f17/?tx_enotepodcast_pi1%5bdata%5d=true` in incognito, then no auth, and there is not suppose to be.

So the auth error must come from something else I would guess.

**Comment by iainbryson** [comment]
The problem is that with the new system, we expand every link on the (main) podcast page.  Currently the page is:

```
Follow the 02402 Podcast [here](https://02402.compute.dtu.dk/podcast). It now contains the last years podcasts, both in Danish and English. During the Spring semester it will be updated by Per every Tuesday.

[Podcast link](http://podcast.llab.dtu.dk/feeds/02402-introduction-to-statistics-f17/?tx_enotepodcast_pi1[data]=true)
```

As you saw, the /podcast.llab.dtu.dk loads just fine (I checked from the container with curl).  But we try and load the other one too.

So we try to load the http://02402... one:

```
[root@42c843a7fc82 app]# curl https://02402.compute.dtu.dk/podcast
<html><body>You are being <a href="https://auth.dtu.dk/dtu/login?service=https%3A%2F%2F02402.compute.dtu.dk%2Fpodcast%2Findex&amp;gateway=true">redirected</a>.</body></html>
```

(curl run from the container)

The fix I put into devel  will not treat the failure as fatal, but it will likely not be what you want for this use-case: you seem to wish to have a mix of both podcast-fetch and non-podcast fetch URLs in the same page. In that case, perhaps we should redesign this to have a different markup for the podcast link (and maybe have them work in any page), rather than specific behavior for a special-named page.

**Comment by dtu-compute** [comment]
I see... Interesting.

Yes, that is exactly what we are after. 

Typing `[Podcast link](http://llab...` should fetct and parse the podcast from llab.dtu.dk where typing `[here](https://02402.compute.dtu.dk/podcast)` is just a normal link.

Typing `[Podcast link](http://google.com)` or any other url from llab that doesn't return the expected podcast json should result in an error.

**Comment by iainbryson** [comment]
Ok.  We can do that.  Do you want all the other extra directives to work on Podcast pages, or not?  i.e. :only and :group etc..?

Another way of asking the same thing: do the podcast pages:
1. Act like any other page. The [Podcast link] behavior works on _any_ page?
2. Act like any other page. The [Podcast link] only works on `Podcast-right`, `Podcast` or `Podcast-left` pages?  Or perhaps just the "main" `Podcast-right`, `Podcast`pages
3. Act differently from the other pages, more similar to the way they are now, except only expanding the [Podcast link] links instead of all the links?

**Comment by dtu-compute** [comment]
> Do you want all the other extra directives to work on Podcast pages, or not? i.e. :only and :group etc..?

It is not needed right now, but from September it will. So it make sense to implement now rather than later, then let's do that =)

As for the 3 options, I can excluse nr. 2, but not sure about 1 and 3 =)

I am temping to say 1, but then 3 says "except only expanding the [Podcast link] links instead of all the links" which sounds like what we are looking for.

Is that the same as "Work on any page, but only expand link if the reserved word `Podcast link` is found? Ie. `[Ruby rocks](http://llab...)` will not expand.

**Comment by iainbryson** [comment]
The main difference between 1 & 3 is whether the other directives work or not.  It's simpler just to say that the podcast pages work like any other page, and just add the [Podcast link] behavior in to the behavior for every page (1).  (2) is almost the same, the only difference being that [Podcast link] does/does not work on any page based on its name.  But everything else is functionally the same.

**Comment by dtu-compute** [comment]
Excellent. Then let's go with 1 =)
