### ISSUE TITLE
-left/-right never goes away

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#71]
In 02323 they have

* created `Agendas`
* created `Agendas-left` and `Agendas-right`
* renamed `Agendas-left` to `xtrash` (as there is no delete in StackEdit)

but it is still on the website even after I have deleted it from `/vol/website-raw/02323`.

**Comment by iainbryson** [comment]
This doesn't seem to be the case right now on https://02323.compute.dtu.dk/Agendas . Did something fix this?

**Comment by dtu-compute** [comment]
In Denmark we have saying that problem doesn't fix them self, which is clearly not true =)

Perhaps StackEdit/Couchdb caches them somehow and only when restarting them the original renamed files goes away?

They are gone from `/vol/website-raw/02323` and the website looks as expected, so I am closing =)

**Comment by iainbryson** [comment]
Yes, this is exactly what’s going on.  The proper fix is to delete (or maybe archive) the old files during the import from stackedit.  This is a real problem and will show up again.
