### ISSUE TITLE
Double () are now needed

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#73]
After the podcast commit were made so podcasts would be inserted, one have to write double `))` to get one `)`. Example:

```
AFTER lecture: Complete the exercises listed below (2 hours))(click the link e.g. [E1.1] links to Chapter 1 Exercise 1)
```

**Comment by iainbryson** [comment]
Do you have a repro case for this?  I'm having a hard time reproducing it here in tests.

**Comment by dtu-compute** [comment]
Typing
```
AFTER lecture: Complete the exercises listed below (2 hours))(click the link e.g. [E1.1] links to Chapter 1 Exercise 1)
```

should output the desired result, but notice `(2 hours))` is required. But if this can't be reproduced with the new editor, then let's close it. https://00000-devel2.compute.dtu.dk/ is down, so I can't test it right now.

**Comment by iainbryson** [comment]
Well that’s incredibly strange.  Some of the cert files are missing on devel2:

```
/vol/certs/sharelatex-00001-enote-devel2.compute.dtu.dk:
total 20
4 drwxr-xr-x  2 root root 4096 Mar 24 00:26 .
4 drwxr-xr-x 19 root root 4096 Mar 24 00:28 ..
4 -rw-r--r--  1 root root 3505 Mar 23 23:49 fullchain.pem
4 -rw-r--r--  1 root root 1704 Mar 23 23:49 privkey.pem
4 -rw-r--r--  1 root root  543 Mar 23 23:49 README

/vol/certs/sharelatex-01005-devel2.compute.dtu.dk:
total 12
4 drwxr-xr-x  2 root root 4096 Mar 24 00:26 .
4 drwxr-xr-x 19 root root 4096 Mar 24 00:28 ..
4 -rw-r--r--  1 root root  543 Feb  2 00:25 README

/vol/certs/stackedit-devel2.compute.dtu.dk:
total 16
4 drwxr-xr-x  2 root root 4096 Mar 24 00:26 .
4 drwxr-xr-x 19 root root 4096 Mar 24 00:28 ..
4 -rw-r--r--  1 root root 3489 Mar 24 00:06 fullchain.pem
4 -rw-r--r--  1 root root 1704 Mar 24 00:06 privkey.pem
```

Do you have a backup of these, or should I re-request them from let’s encrypt?

**Comment by dtu-compute** [comment]
I only have backup of the production server...

**Comment by iainbryson** [comment]
OK.  I’ve created self-signed certs to bootstrap it and am now building the system.

**Comment by iainbryson** [comment]
I've updated the certs properly.

It seems the issue #73 is resolved, if I understand it correctly:

https://00000-devel2.compute.dtu.dk/newtest

**Comment by dtu-compute** [comment]
It looks like it is fixed. I close =)
