### ISSUE TITLE
Edit certain config values from admin panel

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#74]
The setup is not really designed for this, but how complicated would it be to implement that admin users can edit certain config variables? Example:

* `name` in courses.yaml
* `enote_project_id` in sharelatex.yaml

**Comment by iainbryson** [comment]
This could be relatively straightforward.  Of course changes wouldn’t take effect until the affected pages are reloaded.

**Comment by dtu-compute** [comment]
Perfect.
