### ISSUE TITLE
eNote menu names expand too much

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#75]
If a file is called `ChapterA.pdf` it gets expanded to `Chapter A`. The space should not be added.

**Comment by iainbryson** [comment]
Currently we use String.titleize for this.  Can you give me an idea of what you want each of the following to look like?

```
> ["CamelCaseName", "camelCase2", "ChapterA", "test_file", "__another-example"].map(&:titleize)
 => ["Camel Case Name", "Camel Case2", "Chapter A", "Test File", "Another Example"] 
```

Obviously, `ChapterA` should be changed according to the spec.  But what of the others?

**Comment by dtu-compute** [comment]
The perfect solution would be `ChapterA -> Chapter A` and `Chapter2 -> Chapter 2`. Right now a space is not inserted infront of numbers.

**Comment by iainbryson** [comment]
Here is a set of pages from production that I'll use for the spec.  Does this seem right?  Perhaps you also want to always preserve "eNote" as `eNote` and not `E Note`

[
    [ 0] {
         :in => "eNote 06",
        :out => "E Note 06"
    },
    [ 1] {
         :in => "Kaitel 1",
        :out => "Kaitel 1"
    },
    [ 2] {
         :in => "Kaitel 2 - Ikke lin ligninger",
        :out => "Kaitel 2   Ikke Lin Ligninger"
    },
    [ 3] {
         :in => "kaitel 3 - Part Di",
        :out => "Kaitel 3   Part Di"
    },
    [ 4] {
         :in => "book-IntroStatistics",
        :out => "Book Intro Statistics"
    },
    [ 5] {
         :in => "chater1-DataVisualization",
        :out => "Chater 1 Data Visualization"
    },
    [ 6] {
         :in => "chater2-ProbabilitySimulation",
        :out => "Chater 2 Probability Simulation"
    },
    [ 7] {
         :in => "chater3-StatisticsNormalAssumtion",
        :out => "Chater 3 Statistics Normal Assumtion"
    },
    [ 8] {
         :in => "chater4-SimulationBaseStatistics",
        :out => "Chater 4 Simulation Base Statistics"
    },
    [ 9] {
         :in => "chater5-SimleLinearRegression",
        :out => "Chater 5 Simle Linear Regression"
    },
    [10] {
         :in => "chater6-MultileLinearRegression",
        :out => "Chater 6 Multile Linear Regression"
    },
    [11] {
         :in => "chater7-ProortionsFrequencyTables",
        :out => "Chater 7 Proortions Frequency Tables"
    },
    [12] {
         :in => "chater8-StatisticsMultigrouANOVA",
        :out => "Chater 8 Statistics Multigrou Anova"
    },
    [13] {
         :in => "chaterA-ormulas",
        :out => "Chater A Ormulas"
    }
]
 => nil

**Comment by dtu-compute** [comment]
It is fine that `eNote` becomes `E Note`. No problem.

Would it be possible to preserve words that are all capital such as ANOVA which is often used for Analysis of Variance?

Or should these be made into special cases which are hard coded?

**Comment by iainbryson** [comment]
The solution used in the Rails code itself uses a hardcoded list of acceptable acronyms, so I think that would be the best solution.  Can you get such a list?  

All the infrastrcuture is there now, so we should be able to add that.

**Comment by dtu-compute** [comment]
Ok, I don't really want to have key words hard coded, as the key words might needs to be extended. So let's only have `_` becomes ` `. That way they can control the lower/upper them self and are forced to

**Comment by iainbryson** [comment]
`_` and `.` are already treated specially by the algorithm.  How about we just special case ALLCAPS words to not change them?

i.e. `THe` -> `The` but `THE` -> `THE` ?

That’s likely the most straightforward solution.

**Comment by dtu-compute** [comment]
It was what I was thinking, but I now think the trade off with extra code and harder to document to users, isn't worth it compared to a simple replace underscore to space rule. They can control the rest in ShareLatex.

**Comment by iainbryson** [comment]
The code is easier with just the rule for all caps words, but if it’s easier for users, that seems more important to me anyway.

So I’ll add the following to the spec and make it work (TDD! :) , right?:

```
    [12] {
              :in => "chapter8-StatisticsMultigroupA_N_O_V_A",
        :expected => "Chapter 8 Statistics Multigroup ANOVA",
          :actual => "Chapter 8 Statistics Multigroup a N O v A",
         :correct => false
    },
```

**Comment by dtu-compute** [comment]
It is a shame to throw away code, but the more I think about it the less I like the idea of Ruby altering the filenames besides `_` to ` `.  The professors should rather modify the Latex filenames and that way they can get exactly what they want =)

**Comment by iainbryson** [comment]
Ok. So I change the code to simply remove the .PDF extension, and convert _ to ., And that's it. Correct?

**Comment by dtu-compute** [comment]
Correct. Thanks =)
