### ISSUE TITLE
Take quiz issues

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#76]
I suspect the client-side javascript is not getting set up correctly, so all the actions aren’t getting set up properly.  I don’t know why that would happen, but I have some ideas of how to add better logging to help figure it out.

**Comment by iainbryson** [comment]
This should be in the quiz project, no?

**Comment by dtu-compute** [comment]
I suppose this is a dub of #220. Therefore closing.
