### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#81]
Somehow it should be possible to embed YouTube videos in the pages. Perhaps by
```
See below video for ...

####### begin:youtube
https://www.youtube.com/watch?v=Zaqe0xR-8As
####### end:youtube
```
or perhaps
```
####### youtube https://www.youtube.com/watch?v=Zaqe0xR-8As
```

Or some other syntax that produces less messy server code.

**Comment by iainbryson** [comment]
This should be straightforward.  I favor the single-line syntax unless there's a common use-case around having multiple embeds in sequence.  Otherwise it's simpler to parse and clearer for users.

I'll go with the single-line syntax unless you prefer otherwise.

**Comment by dtu-compute** [comment]
I also like the single line the most, but if the make the code over complicated, then perhaps it isn't work it?

If however it is possible to write html directly in the md file to embed the video, then that isn't a bad solution I'd. I have tried on StackEdit, and I just got a square when
```
<iframe width="420" height="315" src="https://www.youtube.com/watch?v=Zaqe0xR-8As"></iframe> 
```

Couldn't test it on devel2, as I no longer get the admin menu, even though I am admin. Could you test it?

If that or similar works, then let's close this one =)

**Comment by iainbryson** [comment]
This works, but you have to go to get the embed code from YouTube, e.g.:

https://00000-devel2.compute.dtu.dk/youtube

Note that right now the editor does show it in the live preview.  How important is that?

**Comment by dtu-compute** [comment]
I'd say it is perfect, as it is easy to explain how to embed videos =)

I am closing =)
