### ISSUE TITLE
Latex macro support

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#82]
The 01006 exercises make heavy use of macros as seen below, which somehow needs to be supported.

My current thought is that if `macros.md` exist and contains e.g. the below Latex, then the website would post process content in between `$` and `$$` and search and replace with the content in the `macros.md` file.

Example: 
```
bla bla bla $\maengde{100}{kg}$ bla bla bla
```
would become

```
bla bla bla $\left\lbrace \hspace*{-1mm} \begin{array}{c|c} 100 & kg \end{array} \hspace*{-1mm} \right\rbrace$ bla bla bla
```

So the post processing should support `\renewcommand`, `\newcommand`, `\newenvironment`. It might be that one user defined macro is used in one below, so nesting should be possible.

MathJax might not support some of these e.g. I highly doubt `\newcommand{\tref}[2]{\hyperref[#1]{#2 \ref*{#1}}}` would work, but that is no problem as long basic and simple macros are supported. No changes to MathJax should be made.

Can this also be supported for the embedded editor with the live preview? If not, then we create a new ticket for this and prioritise it a bit lower than the other critical tickets.

```
\renewcommand{\chaptername}{Hjemmeopgavesæt}

\newcommand{\bevisslut}{\begin{scriptsize} \begin{flushright} $ \blacksquare $ \end{flushright} \end{scriptsize}}

\newcommand{\tref}[2]{\hyperref[#1]{#2 \ref*{#1}}}
\newcommand{\thref}[2]{\hyperref[#1]{#2}}

\newcommand{\refA}[1]{\colorbox{yellow}{\ref{#1}}}
\newcommand{\hrefA}[2]{\colorbox{yellow}{\href{#1}{#2}}}
\newcommand{\trefA}[2]{\colorbox{yellow}{\hyperref[#1]{#2 \ref*{#1}}}}
\newcommand{\threfA}[2]{\colorbox{yellow}{\hyperref[#1]{#2}}}

\newenvironment{matr}[1]{\hspace*{-.8mm}\begin{bmatrix}\hspace*{-1mm}\begin{array}{#1}}{\end{array}\hspace*{-1mm}\end{bmatrix}\hspace*{-.8mm}}
\newcommand{\transp}{\hspace*{-.6mm}^{\top}}

\newcommand{\maengde}[2]{\left\lbrace \hspace*{-1mm} \begin{array}{c|c} #1 & #2 \end{array} \hspace*{-1mm} \right\rbrace}

\newenvironment{eqnalign}[1]{\setlength{\arraycolsep}{1.3pt}\begin{equation}\begin{array}{#1}}{\end{array}\end{equation}\par}
\newcommand{\eqnl}{\setlength{\arraycolsep}{1.3pt}}

\newcommand{\matind}[3]{{_\mathrm{#1}\mathbf{#2}_\mathrm{#3}}}
\newcommand{\vekind}[2]{{_\mathrm{#1}\mathbf{#2}}}
\newcommand{\jac}[2]{{\mathrm{Jacobi}_\mathbf{#1} (#2)}}
\newcommand{\diver}[2]{{\mathrm{div}\mathbf{#1} (#2)}}
\newcommand{\rot}[1]{{\mathbf{rot}\mathbf{(#1)}}}

\newcommand{\am}{\mathrm{am}}
\newcommand{\gm}{\mathrm{gm}}
\newcommand{\E}{\mathrm{E}}
\newcommand{\Span}{\mathrm{span}}
\newcommand{\mU}{\mathbf{U}}

\newcommand{\ms}{\medskip\\}
\newcommand{\bs}{\bigskip\\}

\newcommand{\mA}{\mathbf{A}}
\newcommand{\mB}{\mathbf{B}}
\newcommand{\mC}{\mathbf{C}}
\newcommand{\mD}{\mathbf{D}}
\newcommand{\mE}{\mathbf{E}}
\newcommand{\mF}{\mathbf{F}}
\newcommand{\mK}{\mathbf{K}}
\newcommand{\mI}{\mathbf{I}}
\newcommand{\mM}{\mathbf{M}}
\newcommand{\mN}{\mathbf{N}}
\newcommand{\mQ}{\mathbf{Q}}
\newcommand{\mT}{\mathbf{T}}
\newcommand{\mV}{\mathbf{V}}
\newcommand{\mW}{\mathbf{W}}
\newcommand{\mX}{\mathbf{X}}
\newcommand{\ma}{\mathbf{a}}
\newcommand{\mb}{\mathbf{b}}
\newcommand{\mc}{\mathbf{c}}
\newcommand{\md}{\mathbf{d}}
\newcommand{\me}{\mathbf{e}}
\newcommand{\mn}{\mathbf{n}}
\newcommand{\mr}{\mathbf{r}}
\newcommand{\mv}{\mathbf{v}}
\newcommand{\mw}{\mathbf{w}}
\newcommand{\mx}{\mathbf{x}}
\newcommand{\mxb}{\mathbf{x_{bet}}}
\newcommand{\my}{\mathbf{y}}
\newcommand{\mz}{\mathbf{z}}
\newcommand{\reel}{\mathbb{R}}
\newcommand{\mL}{\bm{\Lambda}} %Lambda-matrix
\newcommand{\mnul}{\bm{0}}
\newcommand{\trap}[1]{\mathrm{trap}(#1)}
\newcommand{\Det}{\operatorname{Det}}
\newcommand{\adj}{\operatorname{adj}}
\newcommand{\Ar}{\operatorname{Areal}}
\newcommand{\Vol}{\operatorname{Vol}}
\newcommand{\Rum}{\operatorname{Rum}}
\newcommand{\diag}{\operatorname{\bf{diag}}}
\newcommand{\bidiag}{\operatorname{\bf{bidiag}}}
\newcommand{\spanVec}[1]{\mathrm{span}\{#1\}}
\newcommand{\Div}{\operatorname{Div}}
\newcommand{\Rot}{\operatorname{\mathbf{Rot}}}

\newcommand{\Jac}{\operatorname{Jacobi}}
\newcommand{\Tan}{\operatorname{Tan}}
\newcommand{\Ort}{\operatorname{Ort}}
\newcommand{\Flux}{\operatorname{Flux}}
\newcommand{\Cmass}{\operatorname{Cm}}
\newcommand{\Imom}{\operatorname{Im}}
\newcommand{\Pmom}{\operatorname{Pm}}
\newcommand{\IS}{\operatorname{I}}
\newcommand{\IIS}{\operatorname{II}}
\newcommand{\IIIS}{\operatorname{III}}
\newcommand{\Le}{\operatorname{L}}
\newcommand{\app}{\operatorname{app}}
\newcommand{\M}{\operatorname{M}}
\newcommand{\re}{\mathrm{Re}}
\newcommand{\im}{\mathrm{Im}}

\newcommand{\compl}{\mathbb{C}} %de komplekse tal
\newcommand{\e}{\mathrm{e}} %eksponentialfunktionen. lodret 'e', og altså ikke kursiv ligesom andre bogstaver.
```

**Comment by iainbryson** [comment]
This looks actually hopeful: https://docs.mathjax.org/en/latest/misc/faq.html#does-mathjax-support-tex-macros

If that works as advertised then the work would be to create a "special" file `macros.md` which we inject at the beginning of every file.

The question is what is the semantics of this file?  If we simply concatenate `macros.md` at the beginning of the file, then all the  "non-latex" parts of the file would appear in the file.  Is that ok?  Alternatively, we make `macros.md` have an implied $$/$$ wrapping it, it's a little ugly since then the file isn't actually a Markdown file.

**Comment by dtu-compute** [comment]
The ideal solution would be if they could just copy/paste a valid tex file in containing only macros into `macros.md` or perhaps `macros.tex` and when writing a md file, then the inclusion of the macros were invisible to the user.

There are many pages such as e.g. the frontpage which won't be needing the macros, so it would be a shame if they got macros concatenated in the beginning.

Would that be possible?

**Comment by iainbryson** [comment]
I like `macros.tex` if it's only going to be including TeX and not Markdown.

Including it only on certain files is possible. How do we decide which files get the macros and which don't?

Also, will there only ever be one set of macros per course?  Or do you want a syntax which is more like an include, e.g.

###### include macros.tex

?

**Comment by iainbryson** [comment]
Also: Do you have a set of pages I can use for testing/speccing for this?  Ideally a few macros and a few pages which consume them, covering all the desired syntax.

**Comment by dtu-compute** [comment]
Then let's go with `macros.tex`. There will for sure only be one macros file per course, but perhaps something such as `####### include macros.tex` is the best way to include them? The only other way I can think of is doing this would be to have another special file e.g. `macros-pages.txt` which would be a positive list of md files which should have macros included. Don't like that idea so much.

Give me a few moments and I will add a test page here.

**Comment by dtu-compute** [comment]
```
### `\matr`

$$\mr(u,v)=\begin{matr}{c}v\sin(u)+v\cos(u)\\v\e^{\frac{1}{10}\,u}\\v\cos(u)-v\sin(u)\end{matr}\,.$$

$$\displaystyle{\begin{matr}{c}x\\y\end{matr}=\begin{matr}{c}u\cos(v)\\u\sin(v)\end{matr}}\,$$ med oplagte intervaller for $u$ og $v\,.$ Sættes derefter ind i standardparametriseringen for en grafflade. Tjek til sidst normalvektorens retning (afgørende for fluxens fortegn).\bs

### `\maengde`

$ L_{inhom} = \maengde{c_1\e^{-2t}\sin(5t) + c_2\e^{-2t}\cos(5t) + \e^{-\frac{1}{2}t} - \sin(2t)}{t\in\reel,c_1,c_2\in\reel} $ \\

$ L_{inhom} = \maengde{c_1\e^{-2t}\sin(5t) + c_2\e^{-2t}\cos(5t) + \e^{-\frac{1}{2}t} - \sin(2t)}{t\in\reel,c_1,c_2\in\reel} $ \\


**I think there is a typo in the macros file for `\transp`, so let's see how it handles it**

Udregn $\mA\cdot\mA\transp.$

$$f(x_1,x_2,x_3)=P_{\mB}(x_1,x_2,x_3)=\left[x_1\,x_2\,x_3\right]\,\mB \left[x_1\,x_2\,x_3\right]\transp\,$$

### newenvironment

I et sædvanligt retvinklet $(x,y,z)$-koordinatsystem er fire planer $ \alpha_1 $, $ \alpha_2 $, $ \alpha_
3 $ og $ \alpha_4 $ givet ved ligningerne:
\begin{eqnalign}{r@{\hspace*{5mm}}rl}
\alpha_1: & -x +2y +2z &=6 \\
\alpha_2: & 2x - y - z &=0 \\
\alpha_3: & 4x - y -7z &=-2 \\
\alpha_4: & -x -y + 8z &=3 \label{planer}
\end{eqnalign}

### `\matind`

$\matind vFv=\begin{matr}{rrr} \lambda_1 & 0 & 0 \\ 0 & \lambda_2 & 0 \\ 0 & 0 & \lambda_3 \end{matr}=\begin{matr}{rrr} 2 & 0 & 0 \\ 0 & 3 & 0 \\ 0 & 0 & 3 \end{matr}$.\\
```

**Comment by iainbryson** [comment]
A few implementation questions: 
* Do you expect the editor to also be able to edit `macros.tex`?
* Should `macros.tex` show up in the list of pages? (if not, how does one get to do bullet 1 above)?

**Comment by dtu-compute** [comment]
It would be really really good if the editor previewer could display Latex that used macros.

Yes, `macros.tex` should be in the list of pages.

**Comment by iainbryson** [comment]
Do you mean that the editor preview for non-`macros.tex` pages uses macros.tex?  Or that users can edit `macros.tex` in the editor and see some kind of autogenerated preview of _usage_ of the macros?  Both will require some work.  There are 3 options:

1. nothing: edit doesn’t work on `macros.tex`. Users will need to create/update that with git
2. Just-edit: the edit window allows editing `macros.tex`, but there is no preview of it (there’s nothing to preview)
3. Edit-and-preview: The edit allows editing `macros.tex` and shows a preview of the macros.

3 will require a serious design.  It’s not clear how to generate examples of template usage from the templates themselves and there may not be an elegant solution.  2. is possible for tomorrow and 1 is already done (since it involves no work :)

Ok, `macros.tex` will be in the page list.

Should `macros.tex` be visible when you navigate to it?

Finally, we will need to create an error if `macros.md` and `macros.tex` both exist if we chose to make it editable (i.e. 2 or 3 above).  Otherwise the path is not unique (i.e. `course/macros?mode=edit`).  There are other workarounds possible if you really want to be able to edit both, but they’ll need a bit more thought.

**Comment by dtu-compute** [comment]
Ok, so you are asking what should happen if the user opens `macros.tex` in the editor, right? Then option 2.

> Ok, `macros.tex` will be in the page list.

Excellent.

> Should `macros.tex` be visible when you navigate to it?

Not sure I understand this one.

Hm, yes. An error in the parsing list would be great.

What I meant in my previous message was, that if I e.g. have

```
\newenvironment{matr}[1]{\hspace*{-.8mm}\begin{bmatrix}\hspace*{-1mm}\begin{array}{#1}}{\end{array}\hspace*{-1mm}\end{bmatrix}\hspace*{-.8mm}}
```

in `macros.tex` then it could be a really great, if the previewer could display the `\matr`.

**Comment by iainbryson** [comment]
> > Should macros.tex be visible when you navigate to it?
> Not sure I understand this one.

If you go to `course/macros` will it show you the text of `macros.tex`, or look for `macros.md` only ?  Another way of asking the question: "is `macros.tex` edit-only?

> What I meant in my previous message was, that if I e.g. have
` \newenvironment{matr}[1]{\hspace*{-.8mm}\begin{bmatrix}\hspace*{-1mm}\begin{array}{#1}}{\end{array}\hspace*{-1mm}\end{bmatrix}\hspace*{-.8mm}}`

> in macros.tex then it could be a really great, if the previewer could display the \matr.

Do you mean in the edit of `macros.tex` itself or in the edit of a page which consumes the macros? i.e. a page which uses `\matr`?

**Comment by dtu-compute** [comment]
> If you go to course/macros will it show you the text of macros.tex, or look for macros.md only ? Another way of asking the question: "is macros.tex edit-only?

No preferences. What requires less code =)

> Do you mean in the edit of macros.tex itself or in the edit of a page which consumes the macros? i.e. a page which uses \matr?

The last. When I edit a `md` file which uses macros.
