### ISSUE TITLE
Pagedown Extra

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#87]
Do we have Pagedown Extra which adds Definition Lists and should also give Table of contents.

If not, can you add it?

```
Term 1
Term 2
:   Definition A
:   Definition B

Term 3

:   Definition C

:   Definition D

	> part of definition D


### Table of contents

You can insert a table of contents using the marker `[TOC]`:

[TOC]
```

**Comment by iainbryson** [comment]
We already use Pagedown-Extra (though it doesn't show up in the editor right now, that should be easy to fix):

https://00000-devel2.compute.dtu.dk/pagedown_extra

However, note that the definitions don't have a specific styling to them. So while the HTML is producing <dl>, <dt> etc... it doesn't have any particular look to it.  Do you have a style you prefer.

[TOC] is a different matter.  It's not part of Pagedown-Extra (https://github.com/jmcmanus/pagedown-extra , https://michelf.ca/projects/php-markdown/extra/#table ).  It seems to be a custom thing in StackEdit (see public/res/extensions/toc.js).  So it'll be more work to try and extract that and replicate the functionality in the course.

Do you want the 'default' Pagedown-Extra, or Pagedown-Extra plus a TOC extension?

**Comment by dtu-compute** [comment]
It would be great if the editor could render the Definition Lists. The current styling looks perfect. =)

TOC is more of a nice to have, so no point in adding it. default Pagedown-Extra would be great.

**Comment by iainbryson** [comment]
Ok, then we're good here!
