### ISSUE TITLE
Some new pages aren't displayed

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#90]
I have created `Kontakt.md` and I recall seeing it being rendered on the website. Now it is in the list of missing pages, and the website can't see it. The same goes for `Info.md`.

![1](https://cloud.githubusercontent.com/assets/13518486/26541902/fb958c44-4457-11e7-8cee-25646ae4c03f.png)

**Comment by iainbryson** [comment]
Hmm.  This is going to be a challenge.  They seem to show up fine now:

![image](https://cloud.githubusercontent.com/assets/1531103/26559194/0043b364-4463-11e7-974d-05410031ef1d.png)

So that implies that there’s a race condition somewhere where the page won’t show up.  Did you add them to the menu first, before creating them?

**Comment by dtu-compute** [comment]
Interesting! I am close to 100% sure I created `Menu.md` first.

**Comment by iainbryson** [comment]
Ah, ok.  That helps.

Here’s what I can reproduce right now:

When you create a reference to a file which doesn’t exist (e.g. through
Menu.md, but almost certainly through any other reference), we will
generate an error when that is parsed.  We don’t clear that error when the
file is created.  That issue needs to be fixed.

However, I can’t figure out what would cause the issue you’re seeing about
not being able to view or edit a Kontakt, once it is created. The error,
even if it’s old, shouldn’t prevent that from working if the file exists.
Do you recall anything else going on? Or perhaps I misunderstand what you
wrote by “and the website can't see it."

**Comment by dtu-compute** [comment]
Great!

> Or perhaps I misunderstand what you wrote by “and the website can't see it."

I got "Page “Kontakt” or “Kontakt-right” does not exist. Maybe update from the admin page?" when visiting the page.

So I guess the "array" that holds the list of valid pages didn't knew it existed. How does the website know when a page exist? Is it cached somewhere?

The odd thing is that is worked when I made them, and the next day they didn't.

**Comment by iainbryson** [comment]
That's very strange.  The things is, the design for page view works directly off the disk. So there isn't a an array which could get confused like you suggest.  There are both the raw and compiled versions, and the "page doesn't exist" iff the _compiled_ version doesn't exist, but raw and compiled should both exist at the same time.

During git mode transitions there's a lot more going on which could potentially fail.  Did you make any such transition?

I'll play around some more and see if I can't cause this to fail...

**Comment by dtu-compute** [comment]
I am getting it again now in staging, but the first time I clicked on each of the the pages, I got the red box from Rails that the page didn't exist. On the second time I clicked on it, I got the message from before. The front page did fail however. Could it be related to the -left/-right md pages, that mess something up?

On staging`/vol/website-raw/01005/Dagsordner.md` exist, but not `/vol/website/01005/assets/Dagsordner*`

Now I am thinking if several courses have a md file with the same name things mess up?

**Comment by iainbryson** [comment]
Hmm.  There definitely are a lot of differences which doesn’t exist:

```

[root@enote-staging dtu-enote]# ls /vol/website/01005/assets/*.md | xargs
-n 1 basename | sort > x

[root@enote-staging dtu-enote]# ls /vol/website-raw/01005/*.md | xargs -n 1
basename | sort > y

[root@enote-staging dtu-enote]# diff x y

1a2

> Agendas.md

2a4

> DagsordenEU10SD.md

4a7

> DagsordenEU12SD.md

7a11,12

> DagsordenEU2LD.md

> DagsordenEU2SD.md

8a14

> DagsordenEU3SD.md

9a16

> DagsordeneU4SD.md

15a23,26

> DagsordenEU8LD.md

> DagsordenEU8SD.md

> DagsordenEU9LD.md

> DagsordenEU9SD.md

16a28

> DagsordenFU12LD.md

29a42

> DagsordenFU5SD.md

30a44

> DagsordenFU6SD.md

33a48

> Dagsordner.md

41a57

> Material.md

46a63

> OpgEU10LD1.md

52a70,71

> OpgEU10LD8.md

> OpgEU10LD9.md

53a73

> OpgEU10SD1.md

54a75

> OpgEU10SD3.md

55a77

> OpgEU10SD5.md

59a82

> OpgEU11LD1.md

62a86

> OpgEU11SD1.md

67a92,93

> OpgEU11SD7.md

> OpgEU12LD1.md

70a97

> OpgEU12SD4.md

71a99

> OpgEU12SD6.md

76a105

> OpgEU1LD4.md

78a108

> OpgEU1LD7.md

84a115

> OpgEU1SD7.md

86a118

> OpgEU2LD2.md

89a122

> OpgEU2LD6.md

95a129

> OpgEU2SD7.md

97a132,133

> OpgEU3LD1.md

> OpgEU3LD2.md

99a136,137

> OpgEU3LD5.md

> OpgEU3LD6.md

101a140,142

> OpgEU3SD10.md

> OpgEU3SD1.md

> OpgEU3SD2.md

102a144

> OpgEU3SD4.md

116a159

> OpgEU5LD1.md

125a169

> OpgEU6LD3.md

133a178

> OpgEU6SD3.md

135a181

> OpgEU6SD6.md

141a188

> OpgEU7SD4.md

145a193

> OpgEU8LD2.md

152a201

> OpgEU8SD5.md

170a220,221

> OpgFU10LD7.md

> OpgFU11LD1.md

171a223

> OpgFU11LD3.md

172a225

> OpgFU11SD1.md

178a232

> OpgFU12LD2.md

183a238

> OpgFU12SD3.md

185a241

> OpgFU13SD1.md

187a244,245

> OpgFU13SD4.md

> OpgFU13SD5.md

188a247,248

> OpgFU13SD7.md

> OpgFU13SD8.md

200a261

> OpgFU2LD1.md

201a263

> OpgFU2LD3.md

205a268

> OpgFU2SD4.md

206a270

> OpgFU2SD6.md

207a272,273

> OpgFU3LD1.md

> OpgFU3LD2.md

208a275

> OpgFU3LD4.md

215a283

> OpgFU4SD1.md

221a290

> OpgFU5LD1.md

222a292

> OpgFU5LD3.md

228a299

> OpgFU5SD4.md

233a305

> OpgFU6LD1.md

241a314

> OpgFU6SD6.md

246a320,322

> Semesteruge01.md

> Semesteruge01-Opgaver.md

> test.md
```

I’ll look into how that happened.
